### ISSUE TITLE
Is it possible to use meteor data inside subscriptions.

### ISSUE THREAD

**Issue by abhima9yu** [meteor-vue/vue-meteor-tracker#27]
I updated vue-meteor-tracker to the latest version. Now I am facing issues with the code I had with the previous version.

**Previous Code:**

```
export default
   data: ->
      friendIds: null
    
   meteor:
      friendIds: ->  (friend._id for friend in Friends.find().fetch())

      $subscribe:
        'friendsData': -> [@friendIds]
```
The subscription above was working fine with the older version.After upgrdaing I got the following error 

> friendIds: Property already used in the component data, props or other.
        
 I removed friendIds from data as shown below:

**Code after upgradation**

```
export default
   meteor:
      friendIds: ->  (friend._id for friend in Friends.find().fetch())

      $subscribe:
        'friendsData': -> [@friendIds]
```

 Now the subscription is not working properly. Subscription is getting called once with null as params.

Is it possible to use meteor data inside subscriptions? If not what would be the best approach to solve the above issue.

Thanks in advance. Any help would be appreciated.
